// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dndgenesis.Data;

#nullable disable

namespace dndgenesis.Migrations
{
    [DbContext(typeof(dndgenesisContext))]
    [Migration("20220320123535_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dndgenesis.Models.DndClass", b =>
                {
                    b.Property<int>("DndClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DndClassId"), 1L, 1);

                    b.Property<string>("DndClassName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DndClassId");

                    b.ToTable("DndClass");
                });
#pragma warning restore 612, 618
        }
    }
}
